base:
  seed: 42

load_data:
  data_train_path: data/raw/train.csv
  data_test_path: data/raw/test.csv

preprocess_data:
  cols:
    TARGET_COL: 'SalePrice'
    ID_COL: 'Id'
    REAL_COLS:
    - MSSubClass
    - LotFrontage
    - LotArea
    - OverallQual
    - OverallCond
    - YearBuilt
    - YearRemodAdd
    - MasVnrArea
    - BsmtFinSF1
    - BsmtFinSF2
    - BsmtUnfSF
    - TotalBsmtSF
    - 1stFlrSF
    - 2ndFlrSF
    - LowQualFinSF
    - GrLivArea
    - BsmtFullBath
    - BsmtHalfBath
    - FullBath
    - HalfBath
    - BedroomAbvGr
    - KitchenAbvGr
    - TotRmsAbvGrd
    - Fireplaces
    - GarageYrBlt
    - GarageCars
    - GarageArea
    - WoodDeckSF
    - OpenPorchSF
    - EnclosedPorch
    - 3SsnPorch
    - ScreenPorch
    - PoolArea
    - MiscVal
    - MoSold
    - YrSold

    CAT_COLS:
    - MSZoning
    - Street
    - Alley
    - LotShape
    - LandContour
    - Utilities
    - LotConfig
    - LandSlope
    - Neighborhood
    - Condition1
    - Condition2
    - BldgType
    - HouseStyle
    - RoofStyle
    - RoofMatl
    - Exterior1st
    - Exterior2nd
    - MasVnrType
    - ExterQual
    - ExterCond
    - Foundation
    - BsmtQual
    - BsmtCond
    - BsmtExposure
    - BsmtFinType1
    - BsmtFinType2
    - Heating
    - HeatingQC
    - CentralAir
    - Electrical
    - KitchenQual
    - Functional
    - FireplaceQu
    - GarageType
    - GarageFinish
    - GarageQual
    - GarageCond
    - PavedDrive
    - PoolQC
    - Fence
    - MiscFeature
    - SaleType
    - SaleCondition
  paths:
    preprocessed_train_data_pkl: data/interim/train_data.pkl 
    preprocessed_target_data_pkl: data/interim/target_data.pkl
    preprocessed_test_data_pkl: data/interim/test_data.pkl

generate_features:
  cols:
    YEAR_SOLD: 'YrSold'
    YEAR_BUILT: 'YearBuilt'
    BUILDING_AGE: 'BuildingAge'
    HAS_FENCE: 'HasFence'
    HAS_POOL: 'HasPool'
  paths:
    featurized_train_data_pkl: 'data/interim/featurized_train_data_pkl'
    featurized_test_data_pkl: 'data/interim/featurized_test_data_pkl'


train_models:
  cols:
    REAL_COLS:
    - MSSubClass
    - LotFrontage
    - LotArea
    - OverallQual
    - OverallCond
    - YearBuilt
    - YearRemodAdd
    - MasVnrArea
    - BsmtFinSF1
    - BsmtFinSF2
    - BsmtUnfSF
    - TotalBsmtSF
    - 1stFlrSF
    - 2ndFlrSF
    - LowQualFinSF
    - GrLivArea
    - BsmtFullBath
    - BsmtHalfBath
    - FullBath
    - HalfBath
    - BedroomAbvGr
    - KitchenAbvGr
    - TotRmsAbvGrd
    - Fireplaces
    - GarageYrBlt
    - GarageCars
    - GarageArea
    - WoodDeckSF
    - OpenPorchSF
    - EnclosedPorch
    - 3SsnPorch
    - ScreenPorch
    - PoolArea
    - MiscVal
    - MoSold
    - YrSold

    CAT_COLS:
    - MSZoning
    - Street
    - Alley
    - LotShape
    - LandContour
    - Utilities
    - LotConfig
    - LandSlope
    - Neighborhood
    - Condition1
    - Condition2
    - BldgType
    - HouseStyle
    - RoofStyle
    - RoofMatl
    - Exterior1st
    - Exterior2nd
    - MasVnrType
    - ExterQual
    - ExterCond
    - Foundation
    - BsmtQual
    - BsmtCond
    - BsmtExposure
    - BsmtFinType1
    - BsmtFinType2
    - Heating
    - HeatingQC
    - CentralAir
    - Electrical
    - KitchenQual
    - Functional
    - FireplaceQu
    - GarageType
    - GarageFinish
    - GarageQual
    - GarageCond
    - PavedDrive
    - PoolQC
    - Fence
    - MiscFeature
    - SaleType
    - SaleCondition
    - HasPool
    - HasFence

  train_test_split_train_size: 0.8

  paths:
    hyperopt_best_model_path: 'models/hyperopt_best_model.joblib'
    catboost_best_model_path: 'models/catboost_best_model.joblib'

  hyperopt:
    max_evals: 50
    trial_timeout: 30

  catboost:
    iterations: 1000
    learning_rate: 0.02
    eval_metric: 'R2'

predict_n_eval:

  hyperopt:
    metrics: 'reports/hyperopt_metrics.json'
    inference_predict: 'data/processed/hyperopt_predict.csv'

  catboost:
    metrics: 'reports/catboost_metrics.json'
    inference_predict: 'data/processed/catboost_predict.csv'
